### ISSUE TITLE
Paginate-Scroll settings non-operational for some books after changing from scroll to paginate

### ISSUE THREAD

**Issue by jbdalton** [NYPL-Simplified/webpub-viewer#133]
For some books, if the user changes from the default paginate-mode to scroll-mode, then scrolls down before changing back to paginate-mode, they will encounter an unusable "floating" scroll/paginate/font menu that does nothing when they tap it.  This doesn't always happen the first time you toggle like that, but if you toggle back and forth while paging through some books long enough it seems to always happen.

The result of this issue is it leaves the user stuck in a scenario where the only way they can leave the book or change the page/scroll setting is to click in the top left corners of the viewport, where the menu _should_ be, not on the  visible menu (which is floating in the middle or bottom of the screen) itself.  I've recreated this in two books so far, but it's likely in some others.  Duplicated both on my phone iOS 10 / Apple 6, and on the Browserstack real-device emulator for Apple 7 iOS 10.3 in this title: https://qa.subwaylibrary.com/book/dont-blink-james-patterson.html

The other title I've spotted this in is https://qa.subwaylibrary.com/book/remains-day-kazuo-ishiguro.html

Steps to recreate:

1. Start in pagination mode.
2. Go to a book page and change to scroll mode.
3. Scroll a bit while leaving the settings mode open
4. Change back to paginate via the open settings menu
5. Tap screen to close top-settings menu
6. When reopening the setting-menu, it appears to float down the page (under the book-title name or even lower).
7. Clicking on the settings buttons now doesn't do anything.  You have to click the "ghost" area  at the top, where top-settings would normally would be located.

![floating_top_menu](https://cloud.githubusercontent.com/assets/1854259/26416245/31436f4c-4083-11e7-87bb-b14306381b5f.jpg)

**Comment by jbdalton** [comment]
I was able to duplicate the issue in the next 3 books I tried, so I'm either getting better at duplicating it, or this might affect more books than I thought.  

https://qa.subwaylibrary.com/book/open-city-teju-cole.html
https://qa.subwaylibrary.com/book/nest-cynthia-daprix-sweeney.html
https://qa.subwaylibrary.com/book/just-kids-patti-smith.html

These are the updated steps.

1. Open read-now
2. Tap forward through the cover, toc, and front-matter to a chapter that has more than a few pages.
3. Select scrolling from the top-menu options (leave options open)
4. Scroll down only 1/2 a page
5. Select paginated in the open top-menu
6. Tap on middle of page to close top-menu
7. Tap on middle of page again

**Comment by jbdalton** [comment]
This bug seems to affect all books, but only in the latest iOS versions (10.x and above) .   When we tried to duplicate on Amy's iOS 9.x device, the scroll toggle bug is not there.  But I can duplicate the bug on my device (iOS 10.1) and when using the emulators for iOS 10.3 on various apple devices.

Attaching screen caps for emulator on iPad Pro viewing the same page with iOS 10.3 and iOS 9.3.

iPad Pro iOS 10.3:
![ios10-3_scrollbug](https://cloud.githubusercontent.com/assets/1854259/26456707/e405489a-413b-11e7-9bc7-d5b987b94d0d.jpg)

iPad Pro iOS 9.3:
![ios09-3_no_scrollbug1](https://cloud.githubusercontent.com/assets/1854259/26456706/e403fc88-413b-11e7-9e9b-8efcb921f177.jpg)

![ios09-3_no_scrollbug2](https://cloud.githubusercontent.com/assets/1854259/26456991/b497b754-413c-11e7-8fbe-376e8f57b4e8.jpg)

**Comment by aslagle** [comment]
That's weird, mine is iOS 10.2, so I wouldn't expect it to work in 10.2 but neither 10.1 nor 10.3.

**Comment by jbdalton** [comment]
Oops - typo by me:  my device is 10.3.1 iOS, not 10.1.  So the bug is affecting the latest major iOS version 10.3.x but not versions before that.

**Comment by jbdalton** [comment]
Looks good in manual testing now on my iOS 10.3.1 device and the emulator for 10.3.x.
