### ISSUE TITLE
In settings, there's no way to tell which view is selected from a screen reader.

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/webpub-viewer#46]

**Comment by ricardoom** [comment]
@aslagle I was able to add the check icon into this branch and was able to get to show and hide via css. A couple things I could use some guidance on:

1.  _BookSettingsTest.ts_ is complaining again b/c there is a new `svg` icon in the `<button>` 
2. I'd like to add `aria-label` but I need help adding the logic to test for the active reading style. Something along the lines of toggling each button's aria-label depending on which is the current mode. So if paginated mode is the active mode it would be: `aria-label="Paginated mode enabled"` and scrolling would read `Scrolling mode disabled`

you can see where I'm at by checking out [a11y-fix-#46](https://github.com/NYPL-Simplified/webpub-viewer/tree/a11y-fix-%2346)

**Comment by aslagle** [comment]
@ricardoom I fixed those things on your branch. This looks great.

**Comment by aslagle** [comment]
I also went ahead and added your branch into https://github.com/NYPL-Simplified/webpub-viewer/pull/85
