### ISSUE TITLE
Make it easier to get to the navigation elements from a screen reader

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/webpub-viewer#48]
The contents and settings menus at the top from JAWS, and the chapter buttons at the bottom from any screen reader.

**Comment by wlla** [comment]
Correct invalid ARIA attibute values for toc and settings button elements.

**Button element**: `<button class="contents" aria-labelledby="contents" aria-haspopup="true" aria-expanded="true">`
**Invalid ARIA attribute value**: `aria-labelledby="contents"`

**Button element**: `<button class="settings" aria-labelledby="settings-menu" aria-expanded="false" aria-haspopup="true">`
**Invalid ARIA attribute value**: `aria-labelledby="contents"`
