### ISSUE TITLE
Add header to contents view

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/webpub-viewer#49]

**Comment by aslagle** [comment]
This was going to add a "Table of Contents" header at the top of the contents view. I don't think that will be necessary anymore once #29 is done - it was mostly so it was obvious you were in the table of contents when you opened the book, since you hadn't clicked a button to get to it.

@ricardoom what do you think?

**Comment by ricardoom** [comment]
@aslagle yes lets close this.
