### ISSUE TITLE
:cake: class to TOC & Settings buttonsw on click/tap

### ISSUE THREAD

**Issue by ricardoom** [NYPL-Simplified/webpub-viewer#55]
I want to add some ````css```` transitions on click / press; when the ````settings```` button is pressed / clicked I'd like a class added here:
https://github.com/NYPL-Simplified/webpub-viewer/blob/mta-style/src/IFrameNavigator.ts#L75

and similarly on press again, change it back. so the default / initial class would be ````inactive```` and on press / click it would be ````active```` 

I think similarly we'll want to add active / inactive to the TOC button as well...

I can add the inactive classes, but need help w/ the changing them on press/tap.

I know today is busy, so it doesnt need to be hight priority...

**Comment by aslagle** [comment]
You want it on the view, not the button, right @ricardoom ?

**Comment by aslagle** [comment]
pushed to mta-style branch. I added classes to the top and bottom nav as well.
