### ISSUE TITLE
Border in book selection overlaps the first character of adjacent first lane titles.

### ISSUE THREAD

**Issue by jbdalton** [NYPL-Simplified/webpub-viewer#56]
But only seems to occur in the 1st lane  (Mysteries & Suspense on my reader). 

Device: iOS [10.3](url) 
phone: IPhone 6

![selection_overlap_error_first_lane](https://cloud.githubusercontent.com/assets/1854259/25395448/0df0b3f0-29af-11e7-9e82-49f45b6b6c10.PNG)

**Comment by aslagle** [comment]
Moved to https://github.com/NYPL-Simplified/web-reader-landing-page/issues/37

@jbdalton that other repo is for the catalog pages and book description pages, this one has the reader.
