### ISSUE TITLE
showing / hiding in css?

### ISSUE THREAD

**Issue by ricardoom** [NYPL-Simplified/webpub-viewer#60]
is it possible to remove the inline showing /hiding on these two lines:
https://github.com/NYPL-Simplified/webpub-viewer/blob/master/src/IFrameNavigator.ts#L77
https://github.com/NYPL-Simplified/webpub-viewer/blob/master/src/IFrameNavigator.ts#L78
and just have it controlled purely w/ css?

**Comment by aslagle** [comment]
probably - the active/inactive classes could control it. would that be helpful?

**Comment by ricardoom** [comment]
i think so. maybe we can make a branch to explore it.

**Comment by aslagle** [comment]
Started this branch https://github.com/NYPL-Simplified/webpub-viewer/tree/show-hide-with-css

I'll need to fix tests later if we stick with it.

**Comment by ricardoom** [comment]
great. thanks. I'll probably have to work on it tonight.
