### ISSUE TITLE
Use single on/off toggle for Paginated/Scrolling?

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/webpub-viewer#73]
This has been an ongoing discussion between Amy and Ricardo.  Tracking it here.  Delete if it's a dupe. 

@JamesEnglish can prioritize.

**Comment by aslagle** [comment]
Related to #46

**Comment by ricardoom** [comment]
I thought we decided to add an icon to the active state?

**Comment by ricardoom** [comment]
duplicated by #46
