### ISSUE TITLE
Include book title in webreader header?

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/webpub-viewer#76]
Did we remove the title from the header on purpose?  During testing, there's now no indication in the webreader what book you're reading.   Maybe not a big deal for the occasional user, but disconcerting.

For James to prioritize.

**Comment by aslagle** [comment]
@RobKelley It is the title of the page, and it's also displayed at the top after you tap the middle to hide the controls.

**Comment by aslagle** [comment]
@RobKelley please reopen this if there's still something that needs to be fixed.
