### ISSUE TITLE
Ebook doesn't open on Desktop, IE 11 (blank page)

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/webpub-viewer#86]
Also reported by MTA during their review 

I have reproduced locally:  
 ![image](https://cloud.githubusercontent.com/assets/145462/25626255/ee3def0e-2f2c-11e7-9fd8-7a90a6045a67.png)

**Comment by aslagle** [comment]
What versions of IE do we need to support?

**Comment by RobKelley** [comment]
Per @jdalton 

Windows 7
- Internet Explorer 11

Windows 10
- Edge 14

other OS's and browsers now in testing doc: 
https://docs.google.com/document/d/1vWUnDdfMDd1cjJ274PbOo87PWtsp_m7stbA-CqJXTuE/edit
