### ISSUE TITLE
Evaluate magnification options

### ISSUE THREAD

**Issue by wlla** [NYPL-Simplified/webpub-viewer#89]
Zooming is disabled in both frames of the book reader; zooming should not be disabled.

**Comment by aslagle** [comment]
I disabled zooming on purpose because it breaks everything really badly. We need zooming even with our own font size controls?

**Comment by seanredmond** [comment]
The font control doesn't do anything about the size of the controls themselves, so I can image someone wanting to zoom in in to be able to read "paginated."

**Comment by wlla** [comment]
Per discussion am closing this and representing elsewhere.
